# https://docs.confluent.io/platform/current/installation/docker/operations/monitoring.html#use-jmx-monitor-docker-deployments
# https://adkarigar004.medium.com/getting-started-with-apache-kafka-and-prometheus-jmx-javaagent-on-windows-dockertoolbox-b1df3fe5fc7e

version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    #user: "0" # id
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883   
    restart: unless-stopped
    networks:  
      - mqtt_kafka
      - sismo

volumes:
  mosquitto:

networks:
  mqtt_kafka:  
  sismo:
    external: true