# https://docs.confluent.io/platform/current/installation/docker/operations/monitoring.html#use-jmx-monitor-docker-deployments
# https://adkarigar004.medium.com/getting-started-with-apache-kafka-and-prometheus-jmx-javaagent-on-windows-dockertoolbox-b1df3fe5fc7e

version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090   
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    user: "0"
    ports:
      - "3000:3000"
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
     ZOOKEEPER_CLIENT_PORT : 9091
     ZOOKEEPER_TICK_TIME : 2000

    volumes:
      - zookeeper:/zookeeper
    ports:
      - 9091:9091
    restart: unless-stopped
    
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
      - prometheus
    environment:
      CLUSTER_ID : 'q1Sh-9_ISia_zwGINzRvyQ'
      KAFKA_BROKER_ID : 1
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:9091
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_INTER_BROKER_LISTENER_NAME : PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1
      KAFKA_METRICS: 9093      
      KAFKA_OPTS: "-javaagent:/kafka/prometheus/jmx_prometheus_javaagent-0.18.0.jar=9093:/kafka/prometheus/kafka_broker.yml"                            
    volumes:
      - kafka:/kafka
      - ./prometheus:/kafka/prometheus
    ports:
     - 9092:9092
     - 9093:9093
     - 29092:29092
    restart: unless-stopped

volumes:
  zookeeper:
  kafka:
  prometheus:
  grafana:
