# https://docs.confluent.io/platform/current/installation/docker/operations/monitoring.html#use-jmx-monitor-docker-deployments
# https://adkarigar004.medium.com/getting-started-with-apache-kafka-and-prometheus-jmx-javaagent-on-windows-dockertoolbox-b1df3fe5fc7e

version: '3.9'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    #user: "0" # id
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - target: 1883
        host_ip: 0.0.0.0
        published: "1883"
        protocol: tcp
        mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:  
      - mqtt_kafka
      - sismo      
    restart: unless-stopped
 
volumes:
  mosquitto:

networks:
  mqtt_kafka:  
  sismo:
    external: true