version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_container
    user: "0" # id
    environment:
      MONGO_INITDB_ROOT_USERNAME: sismo 
      MONGO_INITDB_ROOT_PASSWORD: "%@K97X+eN&ucQuEm" 
      MONGO_INITDB_DATABASE: sismo      
    ports:
      - 27017:27017   
    restart: unless-stopped
    networks:  
      - mqtt_kafka
      - sismo

volumes:
  mongodb:

networks:
  mqtt_kafka:  
  sismo:
    external: true 